import { Injectable } from '@angular/core';

@Injectable()
export class SharedServiceService {
    storePYpValue: number;
    signPostFlagPYpValue: number;
    storePpValue: number;
    signPostFlagPpValue: number;
    storePtValue: number;
    signPostFlagPtValue: number;
    storePeValue: number;
    signPostFlagPeValue: number;
    storeVeValue: number;
    signPostFlagVeValue: number;
    storeAApValue: number;
    signPostFlagAApValue: number;
    storeBApValue: number;
    signPostFlagBApValue: number;
    storeDDlValue: number;
    signPostFlagDDlValue: number;
    storeDdValue: number;
    signPostFlagDdValue: number;
    storeDdnextValue: number;
    signPostFlagDdnextValue: number;
    storeDd1hrlimValue: number;
    signPostFlagDd1hrlimValue: number;
    storeDd1hrcurrValue: number;
    signPostFlagDd1hrcurrValue: number;
    storeDd1hrnextValue: number;
    signPostFlagDd1hrnextValue: number ;
    storePicurrValue: number;
    signPostFlagPicurrValue: number ;
    storePinextValue: number;
    signPostFlagPinextValue: number;
    storeDiffPiValue: string = 'Constant';
    storePiLimValue: string = "Decreasing";
    storeSignPostFlagPiLimValue: string = "Slightly Decreasing";
    storeVcLimValue: number;
    signPostFlagVcLimValue: number;
    storeVccurrValue: number;
    signPostFlagVccurrValue: number;
    storeVsLimValue: number;
    signPostFlagVsLimValue: number;
    storeVscurrValue: number;
    signPostFlagVscurrValue: number;
    storeMbhpLimValue: number;
    signPostFlagMbhpLimValue  : number;
    storeMbhpCurrValue: number;
    signPostFlagMbhpCurrValue : number;
    storeFwhtLimValue: number;
    signPostFlagFwhtLimValue: number;
    storeFwhtCurrValue: number;
    signPostFlagFwhtCurrValue: number;
    storeAcouLimValue: string = 'Spiking';
    signPostFlagAcouLimValue: string = 'Unstable';
    storeAcouCurrValue:  string = 'Stable';
    signPostFlagSkinLimValue: string = 'Slight Increasing';
    storeSkinLimValue:  string = 'Rapid Increasing';
    storeSKcurrValue: number;
    storeSKnextValue: number;
    storeDiffSKValue: string = "Constant";
    storeKhLimValue: string = "Rapid Increasing";
    signPostFlagKhLimValue : string = 'Slight Increasing';
    storeKhcurrValue: number ;
    storeKhnextValue: number;
    storeKHDiffValue: string = "Constant";
    storeDepLimValue: number ;
    signPostFlagDeplimValue: number;
    storeDepCurrValue: number = 0;
    signPostFlagDepcurrValue: number;
    storeRiskLimValue: string = "H";
    signPostFlagRiskLimValue: string = "M";
    storeRiskCurrValue: string = "M";
    storePypCommValue: string = "Put your comment here";
    storePpCommValue: string = "Put your comment here";
    storePtCommValue: string = "Put your comment here";
    storePeCommValue: string = "Put your comment here";
    storeAapCommValue: string = "Put your comment here";
    storeAcouCommValue: string = "Put your comment here";
    storeBapCommValue: string = "Put your comment here";
    storeDDCommValue: string = "Put your comment here";
    storeDD1hrCommValue: string = "Put your comment here";
    storeDepCommValue: string = "Put your comment here";
    storeFwhtCommValue: string = "Put your comment here";
    storeKHCommValue: string = "Put your comment here";
    storeMbhpCommValue: string = "Put your comment here";
    storePiCommValue: string = "Put your comment here";
    storeRiskCommValue : string = "Put your comment here";
    storeSkinCommValue: string = "Put your comment here";
    storeVcCommValue: string = "Put your comment here";
    storeVsCommValue: string = "Put your comment here";
    storeVeCommValue: string = "Put your comment here";
    storeAapOwnValue: string = "Owner's name";
    storeAcouOwnValue: string = "Owner's name";
    storeBapOwnValue:string = "Owner's name";
    storeDdOwnValue:string = "Owner's name";
    storeDd1hrOwnValue: string = "Owner's name";
    storeDepOwnValue : string = "Owner's name";
    storeFwhtOwnValue: string = "Owner's name";
    storeKhOwnValue: string = "Owner's name";
    storeMbhpOwnValue: string = "Owner's name";
    storePeOwnValue: string = "Owner's name";
    storePiOwnValue : string = "Owner's name";
    storePpOwnValue: string = "Owner's name";
    storePtOwnValue: string = "Owner's name";
    storePypOwnValue: string = "Owner's name";
    storeRiskOwnValue: string = "Owner's name";
    storeSkinOwnValue: string = "Owner's name";
    storeVcOwnValue: string = "Owner's name";
    storeVsOwnValue: string = "Owner's name";
    storeVeOwnValue: string = "Owner's name";
    storeFlowCurrValue: number;
    storeFlowNextValue: number;
    storePypFlagValue: number;
    storeBapFlagValue: number;
    storeAApFlagValue: number;
    storeDDFlagValue: number;
    storeDD1hrFlagValue : number;
    storeDepFlagValue: number;
    storeFwhtFlagValue: number;
    storeMbhpFlagValue: number;
    storePeFlagValue: number;
    storePpFlagValue: number;
    storePtFlagValue: number;
    storeVeFlagValue: number;
    storeVcFlagValue: number;
    storeVsFlagValue: number;

    constructor() {}
}